/*
 * SpeakerDriver.c
 *
 * You need to #define SpeakerFreqTimer as one of the A timers so we can set it up properly
 * You need to #define SpeakerX with X being a number between 1-6 this is so we can set up the interrupt to generate its frequency
 * This driver cannot support more than 6 speakers at a time and all speakers will be controlled by the same Timer
 *
 *  Created on: Feb 4, 2024
 *      Author: blomecj
 */
//All Speakers initialized in this driver are required to have frequencies generated by the same clock
//This means that the limit of our number of speakers is the number of CCR units
//Clock should be set to Continuous Mode
//Relevant CCR Units (we can use #ifdefs to filter)
//  OutMod=Toggle
//  interupt enabled
//

//The ISRs will be in #if FreqTimer == Timer_A0 and we will just have a lot of those (probably only setup for TimerA timers and that will just need to be said in documentation)
//#ifdef SpeakerX blocks where X corresponds to the number of the CCR unit it should be controlled by should surround cases in switch/if statement
//when SpeakerX is defined it should be defined with a bitmask for a pin


void initSpeakerFreqTimer(void * SpeakerFreqTimer){

//    SpeakerFreqTimer->CCTL[1] = (TIMER_A0->CCTL[1]) | TIMER_A_CCTLN_OUTMOD_3; Need to set this up in a way that it will setup the CCTL of the proper CCR units
    //TODO find correct values on technical reference manual setup EX0 because we need prescale of 48
    SpeakerFreqTimer->CTL |= TIMER_A_CTL_MC_1 | TIMER_A_CTL_ID_3 | TIMER_A_CTL_TASSEL_2;//bitmask to set MC to be UP counter TASSEL to use SMCLCK prescalar 4
}



/*
 *
 */
//TODO create initSpeaker(Port#, PinBitmask) you will need to init each speaker individually
void initSpeaker(void * port, char PinBitmask, void * SpeakerFreqTimer){
    initSpeakerFreqTimer(SpeakerFreqTimer);

    port->DIR |= PinBitmask;            // set pin as output
    port->SEL1 &= ~PinBitmask;          // Option 0b10 because that is where premapped Timer Outputs are
    port->SEL0 |= PinBitmask;           //

}

//TODO create playFrequency(Port#, PinBitmask, Freq) to enable note changing


//TODO Create Freq ISR/ISRs if we use both CCR0 and any of the other ones
//ISR FLOW
//  if/switch statement to choose the proper CCR unit
//  clear appropriate int Flag
//  move CCR unit up another half period
//  return to normal program flow
